language: node_js
node_js:
  - "6.11.2"
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  # - npm install -g karma-cli
  - npm install -g mocha
  - npm install -g rollup
  - npm install -g codecov
  - npm install
script:
  - npm test
  - codecov
